version: '3'

services:
  business-cockpit-mongo:
    image: mongo:4.4
    container_name: business-cockpit-mongo
    restart: "no"
    ports:
      - "27017:27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs-business-cockpit", "--bind_ip_all" ]
  business-cockpit-mongo-setup:
    image: business-cockpit-mongo-setup
    build: ./mongo/
    container_name: business-cockpit-mongo-setup
    restart: "no"
    depends_on:
      - business-cockpit-mongo
    volumes:
      - "./mongo:/config"
